import { defineField, defineType } from "sanity";

export const recipe = defineType({
  name: "recipe",
  title: "Recipe",
  type: "document",
  fields: [
    defineField({ name: "title", title: "Recipe title", type: "string", validation: (Rule) => Rule.required() }),
    defineField({
      name: "slug",
      title: "URL slug",
      description: "Just click \"Generate\" — this becomes the recipe's web address, e.g. savrnutrition.co.za/recipes/creamy-tomato-pasta.",
      type: "slug",
      options: { source: "title" },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "excerpt",
      title: "Short description",
      description: "One sentence shown on the recipe's card. If left blank, the card just shows the title.",
      type: "text",
      rows: 2,
    }),
    defineField({
      name: "category",
      title: "Category",
      description: "Which filter tab this recipe shows under on the Recipes section.",
      type: "string",
      options: {
        list: [
          "Chicken",
          "Pasta",
          "Rice",
          "Vegetables",
          "Meal Prep",
          "High Protein Lunches",
          "High Protein Dinners",
          "Quick Meals (under 15 min)",
        ],
      },
    }),
    defineField({
      name: "flavour",
      title: "SAVR flavour used",
      description: "Pick from the flavours already set up under \"Flavours\".",
      type: "reference",
      to: [{ type: "flavour" }],
    }),
    defineField({
      name: "image",
      title: "Photo",
      description: "Click to upload a photo, then drag to set the focal point. Shown on the card and the recipe page.",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({
      name: "prepTime",
      title: "Prep time (minutes)",
      description: "How long to prep before cooking, e.g. 10",
      type: "number",
    }),
    defineField({
      name: "cookTime",
      title: "Cook time (minutes)",
      description: "How long the recipe cooks, e.g. 30",
      type: "number",
    }),
    defineField({
      name: "recipeYield",
      title: "Servings",
      description: "How many servings the recipe makes, e.g. \"4 servings\"",
      type: "string",
    }),
    defineField({
      name: "recipeCuisine",
      title: "Cuisine",
      description: "The cuisine style, e.g. \"South African\", \"Italian\"",
      type: "string",
    }),
    defineField({
      name: "calories",
      title: "Calories per serving",
      description: "e.g. \"450 kcal per serving\"",
      type: "string",
    }),
    defineField({
      name: "recipeIngredient",
      title: "Ingredients list",
      description: "Add each ingredient as a separate item — used by Google Recipe rich results.",
      type: "array",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "recipeInstructions",
      title: "Method steps",
      description: "Add each step as a separate item — used by Google Recipe rich results.",
      type: "array",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "body",
      title: "Full recipe (rich text)",
      description: "Write like a normal document — use the toolbar for bold, lists, and headings.",
      type: "array",
      of: [{ type: "block" }],
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "category", media: "image" },
  },
});
