import { defineField, defineType } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  groups: [
    { name: "pricing", title: "Pricing", default: true },
    { name: "homepage", title: "Homepage copy" },
    { name: "sections", title: "Section headings" },
    { name: "delivery", title: "Delivery" },
    { name: "footer", title: "Footer & Contact" },
  ],
  fields: [
    defineField({
      name: "price",
      title: "Current price (R)",
      description:
        "The price shown and charged right now on the live site. Change this number and the new price is live within about a minute — no developer needed.",
      type: "number",
      group: "pricing",
      validation: (Rule) => Rule.required().positive(),
      initialValue: 299,
    }),
    defineField({
      name: "standardPrice",
      title: "Regular price (R) — shown crossed out",
      description: "Optional reference price shown for comparison. Doesn't affect what customers are charged.",
      type: "number",
      group: "pricing",
      initialValue: 349,
    }),
    defineField({
      name: "heroEyebrow",
      title: "Small label above the headline",
      description: "e.g. \"Savoury protein · Tomato Napoletana\"",
      type: "string",
      group: "homepage",
    }),
    defineField({
      name: "heroHeadline",
      title: "Main headline",
      description: "The big bold title at the very top of the homepage.",
      type: "string",
      group: "homepage",
    }),
    defineField({
      name: "heroSubheadline",
      title: "Subheadline",
      description: "The paragraph just under the main headline.",
      type: "text",
      rows: 3,
      group: "homepage",
    }),
    defineField({
      name: "heroCtaLabel",
      title: "Button text (below headline)",
      description: "e.g. \"Shop Tomato Napoletana\" — the red button next to the price.",
      type: "string",
      group: "homepage",
    }),
    defineField({
      name: "heroStats",
      title: "Stat strip (the 4 boxes under the photo)",
      description: "Each item is a bold number/label plus a smaller line underneath, e.g. \"20g protein\" / \"per 40g serving\".",
      type: "array",
      group: "homepage",
      of: [
        {
          type: "object",
          name: "heroStat",
          fields: [
            defineField({ name: "label", title: "Bold text", type: "string" }),
            defineField({ name: "sub", title: "Smaller text underneath", type: "string" }),
          ],
          preview: { select: { title: "label", subtitle: "sub" } },
        },
      ],
    }),
    defineField({
      name: "aboutCopy",
      title: "\"About SAVR\" text",
      description:
        "Each item below becomes its own paragraph in the About section. Click '+ Add item' to add another paragraph, or the bin icon to remove one.",
      type: "array",
      of: [{ type: "text", rows: 3 }],
      group: "homepage",
    }),
    defineField({
      name: "howToUseSteps",
      title: "\"How to use it\" steps",
      description: "Shown as numbered steps (1, 2, 3...) on the homepage. Add, remove, or reorder as needed.",
      type: "array",
      of: [{ type: "string" }],
      group: "homepage",
    }),
    defineField({
      name: "whyPoints",
      title: "\"Why savoury?\" points",
      description: "Short title + explanation pairs, shown further down the homepage.",
      type: "array",
      group: "homepage",
      of: [
        {
          type: "object",
          name: "whyPoint",
          fields: [
            defineField({ name: "title", title: "Short title", type: "string" }),
            defineField({ name: "body", title: "Explanation", type: "text", rows: 2 }),
          ],
          preview: { select: { title: "title", subtitle: "body" } },
        },
      ],
    }),
    defineField({
      name: "shopHeading",
      title: "Shop section heading",
      type: "string",
      group: "sections",
    }),
    defineField({
      name: "shopIntro",
      title: "Shop section intro line",
      type: "text",
      rows: 2,
      group: "sections",
    }),
    defineField({
      name: "recipesHeading",
      title: "Recipes section heading",
      type: "string",
      group: "sections",
    }),
    defineField({
      name: "recipesIntro",
      title: "Recipes section intro line",
      type: "text",
      rows: 2,
      group: "sections",
    }),
    defineField({
      name: "whyHeading",
      title: "\"Why savoury?\" section heading",
      type: "string",
      group: "sections",
    }),
    defineField({
      name: "foundersHeading",
      title: "Founders section heading",
      type: "string",
      group: "sections",
    }),
    defineField({
      name: "foundersIntro",
      title: "Founders section intro line",
      description: "Only shown once at least one founder has a name filled in.",
      type: "text",
      rows: 2,
      group: "sections",
    }),
    defineField({
      name: "faqHeading",
      title: "FAQ section heading",
      type: "string",
      group: "sections",
    }),
    defineField({
      name: "deliveryNotes",
      title: "Delivery option descriptions",
      description:
        "The small grey text shown under each delivery option at checkout (e.g. \"Collect at your nearest PEP store\"). Prices and delivery timing are calculated automatically and can't be changed here.",
      type: "array",
      group: "delivery",
      of: [
        {
          type: "object",
          name: "deliveryNote",
          fields: [
            defineField({
              name: "method",
              title: "Delivery option",
              type: "string",
              options: {
                list: [
                  { title: "Courier Guy", value: "courierguy" },
                  { title: "PAXI", value: "paxi" },
                  { title: "Collect in Cape Town", value: "collect" },
                ],
              },
            }),
            defineField({ name: "note", title: "Description shown to customers", type: "string" }),
          ],
          preview: { select: { title: "method", subtitle: "note" } },
        },
      ],
    }),
    defineField({
      name: "footerText",
      title: "Footer message",
      description: "Short line shown at the very bottom of every page, next to the copyright.",
      type: "text",
      rows: 2,
      group: "footer",
    }),
    defineField({
      name: "contactEmail",
      title: "Contact email",
      description: "Shown on the Contact section and used as the reply-to address on the site.",
      type: "string",
      group: "footer",
    }),
    defineField({
      name: "instagramHandle",
      title: "Instagram handle",
      description: "e.g. @savr.nutrition — shown on the Contact section.",
      type: "string",
      group: "footer",
    }),
    defineField({
      name: "businessAddress",
      title: "Business address",
      description: "Shown on the Contact section. Doesn't need to be exact down to unit number — general area is fine.",
      type: "text",
      rows: 2,
      group: "footer",
    }),
    defineField({
      name: "returnsPolicy",
      title: "Returns policy (not currently shown on site)",
      description:
        "Not displayed anywhere right now — the live Shipping & Returns page is written directly in code. Leave blank unless a developer tells you otherwise.",
      type: "text",
      rows: 4,
      group: "footer",
    }),
  ],
  preview: {
    prepare: () => ({ title: "Site Settings" }),
  },
});
